### PR TITLE
Generic container detection via `container` PID 1 env variable

### PR DESCRIPTION
**Pull request by Jaakkonen**
1. Fixes LXC container detection (used `grep -q` which produces no output but `if` checked if it's non-empty string)
2. Add check for [Podman](https://github.com/containers/podman) container environment
3. Add generic check for other container environments which expose it in `container` environment variable of PID 1.

### CODE REVIEW

**Comment by carlospolop** [comment]
Hi @Jaakkonen,
Thank you very much for your PR, unfortunately I just moved the functionality you are modifying to the `containerCheck` function.
Could you move your new checks there?

**Comment by carlospolop** [comment]
how is this going?

**Comment by Jaakkonen** [comment]
I'll probably have the time to do this change this weekend.

**Comment by Jaakkonen** [comment]
It seems that Github auto-closed the PR when I redid the changes on top of latest `master`. Reopening...

**Comment by carlospolop** [comment]
Great, thanks!

**Pull request merged**
